# Enable USB + BLE central
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_CENTRAL=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y

# Reduce power saving (since it's USB powered)
CONFIG_ZMK_SLEEP=n